version: '3'
services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  backend:
    image: cekoit00/ds-project-backend:latest
    ports:
      - "8080:8080"
    environment:
      - db_host=mongodb
    depends_on:
      - mongodb
      
  frontend:
    image: cekoit00/ds-project-frontend:latest
    ports: 
      - "8081:8081"
    environment:
      - VITE_BACKEND_API_PATH=backend
      - VITE_BACKEND_API_PORT=8080
    depends_on: 
      - backend

volumes:
  mongodb_data:

