version: '3'
services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  backend:
    image: ds-project:v1.1
    ports:
      - "8080:8080"
    environment:
      - db_host="mongodb"
    depends_on:
      - mongodb

volumes:
  mongodb_data:

